name: Build Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        target: [mipsel-linux-musl]

    steps:
      - uses: actions/checkout@main

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt upgrade
          sudo apt-get -y install
            cmake \
            gperf \
            help2man \
            libtool-bin \
            libncurses5-dev \
            libmpfr-dev \
            libmpc-dev \
            libgmp3-dev \
            libltdl-dev \
            libexpat-dev \
            autopoint \
            gettext \
            python3-docutils \
            build-essential
            
          # 强制验证 texinfo 是否安装成功
          makeinfo --version || { echo "❌ texinfo 未安装"; exit 1; }  
          libtool --version || { echo "❌ libtool 未安装"; exit 1; }  
          echo "PATH=$PATH"  # 检查环境变量

      - name: Build and Package
        working-directory: toolchain
        run: |
          # 强制清除可能的残留配置
          make clean CT_TARGET=${{ matrix.target }}
          # 强制从源码构建，跳过下载预编译包
          make CT_TARGET=${{ matrix.target }} || true 
          # 确保打包路径正确
          cd "${{ matrix.target }}"
          tar cJf "../${{ matrix.target }}.tar.xz" .

          echo "Copying build logs for artifact upload..."
          mkdir -p ${{ github.workspace }}/ct_build_logs
          cp -vf .build/mipsel-linux-musl/build.log* ${{ github.workspace }}/ct_build_logs/ || echo "Logs not found"

      - name: Upload build logs on failure or success
        uses: actions/upload-artifact@main
        with:
          name: mipsel-linux-musl-build-logs
          path: ${{ github.workspace }}/ct_build_logs/

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: toolchain/${{ matrix.target }}.tar.xz

      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: toolchain/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true
