name: Build Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        target: [mipsel-linux-musl]

    steps:
      - uses: actions/checkout@main

      - name: Install Build Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            bison \
            flex \
            gperf \
            help2man \
            libtool-bin \
            texinfo \
            autoconf \
            automake \
            gettext \
            g++ \
            file \
            python3 \
            make \
            wget
          # 验证关键工具是否存在
          libtool --version || exit 1
          which libtool || exit 1

      - name: Build and Package
        run: |
          make CT_TARGET=${{ matrix.target }}
          cd "${{ matrix.target }}"
          tar cJf "../${{ matrix.target }}.tar.xz" .
        working-directory: toolchain

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: toolchain/${{ matrix.target }}.tar.xz

      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: toolchain/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true
