name: Build Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        target: [mipsel-linux-musl]

    steps:
      - uses: actions/checkout@main

      - name: Install Build Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            bison \
            flex \
            gperf \
            help2man \
            libtool-bin \
            zlib1g-dev \
            libncurses5-dev \
            texinfo \
            autoconf \
            automake \
            gettext \
            g++ \
            file \
            python3 \
            make \
            wget \
            xz-utils \
            curl \
            git
          # 强制重新配置 libtool 并验证
          sudo libtool --finish /usr/lib
          libtool --version
          which libtool
          echo "PATH=$PATH"  # 检查环境变量

      - name: Build and Package
        run: |
          # 强制清除可能的残留配置
          make -C toolchain clean CT_TARGET=${{ matrix.target }} || true
          # 强制从源码构建，跳过下载预编译包
          make CT_TARGET=${{ matrix.target }} FORCE_BUILD_TOOLCHAIN=1
          # 确保打包路径正确
          cd "${{ matrix.target }}"
          tar cJf "../${{ matrix.target }}.tar.xz" .
        working-directory: toolchain

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: toolchain/${{ matrix.target }}.tar.xz

      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: toolchain/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true
